### ISSUE TITLE
Having a npm install trouble..   upgraded a few depends versions, but now make file build fail.

### ISSUE THREAD

**Issue by johnda98** [Dodecane/hedera-wallet#3]
I also did a npm install --legacy-peer-deps

im running 

 node -v v16.13.1

that ok ?

npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/admin/hedera-wallet/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.2.0
npm ERR! gyp ERR! command "/Users/admin/.nvm/versions/node/v16.13.1/bin/node" "/Users/admin/hedera-wallet/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/admin/hedera-wallet/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2022-01-30T19_42_18_524Z-debug.log

**Comment by johnda98** [comment]
npm install --legacy-peer-deps

after aupgrade to latest for 


  "sass": "^1.49.7",
    "sass-loader": "^12.4.0",
    "source-map-loader": "^1.0.1",




now a fail on npm run dev

ERROR in ./src/popup/css/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/popup/css/style.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/admin/hedera-wallet/node_modules/sass-loader/dist/index.js:25:24)
 @ ./src/popup/css/style.scss 2:26-142
 @ ./src/popup/index.js


will  update that package and see if it helps

**Comment by johnda98** [comment]
ok coolio.. updated sdk and also balances from BigNumber to type Long in HederaServices.ts

**Comment by johnda98** [comment]
yep last trick did it

**Comment by johnda98** [comment]
yes last trick did it
